#下面这些内容是为了让MyBatis映射
mybatis-plus:
  # 指定Mybatis的实体目录，定义别名
  type-aliases-package: xyz.fjzkuroko.seckill.pojo
  # 指定Mybatis的Mapper文件
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true
spring:
  # 静态资源处理
  resources:
    # 启动默认静态资源处理
    add-mappings: true
    cache:
      cachecontrol:
        # 缓存相应时间，单位为秒
        max-age: 3600
    chain:
      # 资源链启动缓存，默认启动
      cache: true
      # 启用资源链，默认禁用
      enabled: true
      # 启用压缩资源(gzip,brotli)解析，默认禁用
      compressed: true
      # 启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/



  datasource:
    # 数据源名称
    name: defaultDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 数据库驱动
      driver-class-name: com.mysql.jdbc.Driver
      # url
      url: jdbc:mysql://localhost:3306/seckillbilibili?useSSL=false
      username: root
      password: 87654321
      # 初始化大小
      initial-size: 5
      # 最大连接数
      max-active: 20
      # 最小空闲连接数
      min-idle: 5
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000

  # Redis缓存相关配置
  redis:
    database: 0
    host: 192.168.98.3
    password: fjzcentos7redis
    port: 6379
    timeout: 10000
    lettuce:
      pool:
        # 最大连接数，默认为8
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000
        # 最大空闲连接数，默认为8
        max-idle: 100
        # 最小空闲连接数,默认为0
        min-idle: 5

  #    hikari:
#      # 连接池名称
#      pool-name: DataHikariCP
#      # 最小空闲连接数
#      minimum-idle: 5
#      # 空闲连接存活最大时间，默认600000
#      idle-timeout: 180000
#      # 最大连接数，默认10
#      maximum-pool-size: 10
#      # 从连接池返回的连接自动提交
#      auto-commit: true
#      # 连接最大存活时间
#      max-lifetime: 1800000
#      # 连接超时时间默认30000（30s）
#      connection-timeout: 30000
#      # 测试连接是否可用的查询语句
#      connection-test-query: SELECT 1
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    # 开启模板缓存（默认值： true ）
    cache: true
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    servlet:
      #Content-Type 的值（默认值： text/html ）
      content-type: text/html
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 要运⽤于模板之上的模板模式。
    mode: HTML5
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html
# MyBatis SQL打印（方法接口所在的包，不是Mapper.xml
logging:
  level:
    xyz.fjzkuroko.seckill.mapper: debug